=== PedroDpsweb/FormularioPedroSanchez/XML/validador/xsd/preguntes.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="preguntes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pregunta" maxOccurs="unbounded" minOccurs="0">
          <xs:annotation>
            <xs:documentation>0, 1, 2  0, 1, 2</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="tipus"/>
              <xs:element type="xs:string" name="text"/>
              <xs:element type="xs:string" name="opcio" maxOccurs="unbounded" minOccurs="0"/>
              <xs:element type="xs:string" name="resposta"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== PedroDpsweb/FormularioPedroSanchez/XML/validador/xsd/preguntes.xml
<?xml version="1.0" encoding="UTF-8"?>
<preguntes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="preguntes.xsd">
<pregunta id='profe001'>
<tipus>text</tipus>
<text>Extensi� d'un fitxer full d'estill</text>
<resposta>css</resposta>
</pregunta>
<pregunta id='profe002'>
<tipus>text</tipus>
<text>Quin �s nom de l'element arrel d'un document html?</text>
<resposta>html</resposta>
</pregunta>
<pregunta id='profe003'>
<tipus>select</tipus>
<text>Un lle� mort de fam, qu� menja?</text>
<opcio>Carn</opcio>
<opcio>Peix</opcio> 
<opcio>Res, est� mort</opcio>
<resposta>2</resposta> <!-- 0, 1, 2 -->
</pregunta>
<pregunta id='profe004'>
<tipus>select</tipus>
<text>Qu� vol dir XML?</text>
<opcio>X Manage Language</opcio>
<opcio>Extensible Markup Language</opcio> 
<opcio>Llenguatge extrem multiplataforma</opcio>
<resposta>1</resposta> <!-- 0, 1, 2 -->
</pregunta>
</preguntes>
